### ISSUE TITLE
more details in NEWS?

### ISSUE THREAD

**Issue by sckott** [ropensci/cRegulome#9]
👋 

Curious if you could include more details in your NEWS moving forward. These items seem like they could easily be more detailed, e.g. if you reduce code dependencies, i assume that means 1 or more pkgs are no longer imported/suggested/etc. - if so, which ones?

```
cRegulome 0.2.0

- Reduced code dependencies
- Improved code performance
```

**Comment by MahShaaban** [comment]
👋
No problem. 
Do you recommend editing the news file for this release or you only mean I should do that in the future?

**Comment by sckott** [comment]
Moving forward is good, thx

**Comment by sckott** [comment]
thanks for the more details news in the latest release https://github.com/ropensci/cRegulome/blob/master/NEWS.md#cregulome-030  - could you also copy the news items verbatim to the release (https://github.com/ropensci/cRegulome/releases/tag/v0.3.0) for that version? thanks very much

**Comment by sckott** [comment]
oh, and typically in my experience the newest version release notes in news/changelog is at the top, not the bottom, but have you seen it the other way often?

**Comment by MahShaaban** [comment]
I fixed the release notes and the news file as recommended. Thanks.
